import type { BackgroundCheckWithSubject } from '@hr/shared'

export const MOCK_CANDIDATES = [
  { id: 'demo-cand-1', full_name: 'Sarah Njeri Kimani', email: 'sarah.kimani@example.com' },
  { id: 'demo-cand-2', full_name: 'James Odhiambo Otieno', email: 'james.otieno@example.com' },
  { id: 'demo-cand-3', full_name: 'Grace Wanjiku Muthoni', email: 'grace.muthoni@example.com' },
]

export const MOCK_EMPLOYEES = [
  {
    id: 'demo-emp-1',
    employee_number: 'EMP-001',
    user: { full_name: 'Peter Mwangi Kamau', email: 'peter.kamau@company.com' }
  },
  {
    id: 'demo-emp-2',
    employee_number: 'EMP-002',
    user: { full_name: 'Mary Akinyi Ouma', email: 'mary.ouma@company.com' }
  },
]

const now = new Date()
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString()
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString().slice(0, 10)

const DEMO_TENANT_ID = 'demo-tenant-00000000-0000-0000-0000-000000000000'

export const MOCK_BACKGROUND_CHECKS: BackgroundCheckWithSubject[] = [
  {
    id: 'demo-check-1',
    tenant_id: DEMO_TENANT_ID,
    candidate_id: 'demo-cand-1',
    employee_id: null,
    company_id: 'demo-company',
    check_type: 'criminal',
    status: 'pending',
    requested_by: 'demo-user',
    requested_at: daysAgo(2),
    document_url: null,
    document_uploaded_at: null,
    provider_name: null,
    provider_reference: null,
    provider_response: null,
    completed_at: null,
    reviewed_by: null,
    result_summary: null,
    clearance_date: null,
    expiry_date: null,
    flags: [],
    notes: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    is_deleted: false,
    candidate: { full_name: 'Sarah Njeri Kimani', email: 'sarah.kimani@example.com' },
  },
  {
    id: 'demo-check-2',
    tenant_id: DEMO_TENANT_ID,
    candidate_id: 'demo-cand-2',
    employee_id: null,
    company_id: 'demo-company',
    check_type: 'employment',
    status: 'in_progress',
    requested_by: 'demo-user',
    requested_at: daysAgo(5),
    document_url: null,
    document_uploaded_at: null,
    provider_name: null,
    provider_reference: null,
    provider_response: null,
    completed_at: null,
    reviewed_by: null,
    result_summary: null,
    clearance_date: null,
    expiry_date: null,
    flags: [],
    notes: 'Contacting previous employer',
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    is_deleted: false,
    candidate: { full_name: 'James Odhiambo Otieno', email: 'james.otieno@example.com' },
  },
  {
    id: 'demo-check-3',
    tenant_id: DEMO_TENANT_ID,
    employee_id: 'demo-emp-1',
    candidate_id: null,
    company_id: 'demo-company',
    check_type: 'criminal',
    status: 'passed',
    requested_by: 'demo-user',
    requested_at: daysAgo(90),
    document_url: 'https://storage.example.com/pcc/peter-kamau.pdf',
    document_uploaded_at: daysAgo(85),
    provider_name: null,
    provider_reference: null,
    provider_response: null,
    completed_at: daysAgo(85),
    reviewed_by: 'demo-reviewer',
    result_summary: 'No criminal record found. Certificate valid.',
    clearance_date: daysAgo(85).slice(0, 10),
    expiry_date: daysFromNow(275),
    flags: [],
    notes: null,
    created_at: daysAgo(90),
    updated_at: daysAgo(85),
    is_deleted: false,
    employee: {
      employee_number: 'EMP-001',
      user: { full_name: 'Peter Mwangi Kamau', email: 'peter.kamau@company.com' }
    },
  },
  {
    id: 'demo-check-4',
    tenant_id: DEMO_TENANT_ID,
    employee_id: 'demo-emp-2',
    candidate_id: null,
    company_id: 'demo-company',
    check_type: 'criminal',
    status: 'flagged',
    requested_by: 'demo-user',
    requested_at: daysAgo(30),
    document_url: 'https://storage.example.com/pcc/mary-ouma.pdf',
    document_uploaded_at: daysAgo(25),
    provider_name: null,
    provider_reference: null,
    provider_response: null,
    completed_at: daysAgo(25),
    reviewed_by: 'demo-reviewer',
    result_summary: 'Minor traffic violation from 2019. No disqualifying offenses.',
    clearance_date: daysAgo(25).slice(0, 10),
    expiry_date: daysFromNow(340),
    flags: ['minor_offense', 'requires_manager_approval'],
    notes: 'Traffic violation was a minor speeding ticket. Cleared for hire with manager approval.',
    created_at: daysAgo(30),
    updated_at: daysAgo(25),
    is_deleted: false,
    employee: {
      employee_number: 'EMP-002',
      user: { full_name: 'Mary Akinyi Ouma', email: 'mary.ouma@company.com' }
    },
  },
  {
    id: 'demo-check-5',
    tenant_id: DEMO_TENANT_ID,
    candidate_id: 'demo-cand-3',
    employee_id: null,
    company_id: 'demo-company',
    check_type: 'education',
    status: 'passed',
    requested_by: 'demo-user',
    requested_at: daysAgo(60),
    document_url: 'https://storage.example.com/edu/grace-muthoni.pdf',
    document_uploaded_at: daysAgo(55),
    provider_name: null,
    provider_reference: null,
    provider_response: null,
    completed_at: daysAgo(55),
    reviewed_by: 'demo-reviewer',
    result_summary: 'Bachelor of Commerce degree verified with University of Nairobi.',
    clearance_date: daysAgo(55).slice(0, 10),
    expiry_date: null,
    flags: [],
    notes: null,
    created_at: daysAgo(60),
    updated_at: daysAgo(55),
    is_deleted: false,
    candidate: { full_name: 'Grace Wanjiku Muthoni', email: 'grace.muthoni@example.com' },
  },
  {
    id: 'demo-check-6',
    tenant_id: DEMO_TENANT_ID,
    candidate_id: null,
    employee_id: 'demo-emp-1',
    company_id: 'demo-company',
    check_type: 'criminal',
    status: 'passed',
    requested_by: 'demo-user',
    requested_at: daysAgo(400),
    document_url: 'https://storage.example.com/pcc/peter-kamau-old.pdf',
    document_uploaded_at: daysAgo(395),
    provider_name: null,
    provider_reference: null,
    provider_response: null,
    completed_at: daysAgo(395),
    reviewed_by: 'demo-reviewer',
    result_summary: 'No criminal record found.',
    clearance_date: daysAgo(395).slice(0, 10),
    expiry_date: daysAgo(30).slice(0, 10),
    flags: [],
    notes: 'Previous clearance - now expired',
    created_at: daysAgo(400),
    updated_at: daysAgo(395),
    is_deleted: false,
    employee: {
      employee_number: 'EMP-001',
      user: { full_name: 'Peter Mwangi Kamau', email: 'peter.kamau@company.com' }
    },
  },
]

// Stats derived from mock data
export const MOCK_STATS = {
  pending: MOCK_BACKGROUND_CHECKS.filter(c => c.status === 'pending').length,
  inProgress: MOCK_BACKGROUND_CHECKS.filter(c => c.status === 'in_progress').length,
  passed: MOCK_BACKGROUND_CHECKS.filter(c => c.status === 'passed').length,
  failed: MOCK_BACKGROUND_CHECKS.filter(c => c.status === 'failed').length,
  flagged: MOCK_BACKGROUND_CHECKS.filter(c => c.status === 'flagged').length,
  expiring: 1,
  expired: 1,
}
